/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ApplicationStatusRouteImport } from './routes/application-status'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenturesIndexRouteImport } from './routes/ventures.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VenturesSlugRouteImport } from './routes/ventures.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AboutStandardsRouteImport } from './routes/about.standards'
import { Route as AboutMethodologyRouteImport } from './routes/about.methodology'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as AboutAwardsRouteImport } from './routes/about.awards'
import { Route as AboutPillarRouteImport } from './routes/about.$pillar'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin.cms.index'
import { Route as AdminPagesPageRouteImport } from './routes/admin.pages.$page'
import { Route as AdminCmsTypeRouteImport } from './routes/admin.cms.$type'
import { Route as AdminCmsTypeIndexRouteImport } from './routes/admin.cms.$type.index'
import { Route as AdminCmsTypeIdRouteImport } from './routes/admin.cms.$type.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationStatusRoute = ApplicationStatusRouteImport.update({
  id: '/application-status',
  path: '/application-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesIndexRoute = VenturesIndexRouteImport.update({
  id: '/ventures/',
  path: '/ventures/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VenturesSlugRoute = VenturesSlugRouteImport.update({
  id: '/ventures/$slug',
  path: '/ventures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AboutStandardsRoute = AboutStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMethodologyRoute = AboutMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAwardsRoute = AboutAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPillarRoute = AboutPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => AboutRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminPagesPageRoute = AdminPagesPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminCmsTypeRoute = AdminCmsTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsTypeIndexRoute = AdminCmsTypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsTypeRoute,
} as any)
const AdminCmsTypeIdRoute = AdminCmsTypeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCmsTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/$pillar': typeof AboutPillarRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/about/standards': typeof AboutStandardsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/data': typeof AdminDataRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ventures/': typeof VenturesIndexRoute
  '/admin/cms/$type': typeof AdminCmsTypeRouteWithChildren
  '/admin/pages/$page': typeof AdminPagesPageRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/cms/$type/$id': typeof AdminCmsTypeIdRoute
  '/admin/cms/$type/': typeof AdminCmsTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/$pillar': typeof AboutPillarRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/about/standards': typeof AboutStandardsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ventures': typeof VenturesIndexRoute
  '/admin/pages/$page': typeof AdminPagesPageRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/cms/$type/$id': typeof AdminCmsTypeIdRoute
  '/admin/cms/$type': typeof AdminCmsTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/$pillar': typeof AboutPillarRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/about/standards': typeof AboutStandardsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/data': typeof AdminDataRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ventures/': typeof VenturesIndexRoute
  '/admin/cms/$type': typeof AdminCmsTypeRouteWithChildren
  '/admin/pages/$page': typeof AdminPagesPageRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/cms/$type/$id': typeof AdminCmsTypeIdRoute
  '/admin/cms/$type/': typeof AdminCmsTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/application-status'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/about/$pillar'
    | '/about/awards'
    | '/about/leadership'
    | '/about/methodology'
    | '/about/standards'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/data'
    | '/admin/login'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/profile'
    | '/admin/settings'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/ventures/$slug'
    | '/admin/'
    | '/ventures/'
    | '/admin/cms/$type'
    | '/admin/pages/$page'
    | '/admin/cms/'
    | '/admin/pages/'
    | '/admin/cms/$type/$id'
    | '/admin/cms/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/application-status'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/about/$pillar'
    | '/about/awards'
    | '/about/leadership'
    | '/about/methodology'
    | '/about/standards'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/data'
    | '/admin/login'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/settings'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/ventures/$slug'
    | '/admin'
    | '/ventures'
    | '/admin/pages/$page'
    | '/admin/cms'
    | '/admin/pages'
    | '/admin/cms/$type/$id'
    | '/admin/cms/$type'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/application-status'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/about/$pillar'
    | '/about/awards'
    | '/about/leadership'
    | '/about/methodology'
    | '/about/standards'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/data'
    | '/admin/login'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/profile'
    | '/admin/settings'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/ventures/$slug'
    | '/admin/'
    | '/ventures/'
    | '/admin/cms/$type'
    | '/admin/pages/$page'
    | '/admin/cms/'
    | '/admin/pages/'
    | '/admin/cms/$type/$id'
    | '/admin/cms/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApplicationStatusRoute: typeof ApplicationStatusRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  PSlugRoute: typeof PSlugRoute
  VenturesSlugRoute: typeof VenturesSlugRoute
  VenturesIndexRoute: typeof VenturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-status': {
      id: '/application-status'
      path: '/application-status'
      fullPath: '/application-status'
      preLoaderRoute: typeof ApplicationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/': {
      id: '/ventures/'
      path: '/ventures'
      fullPath: '/ventures/'
      preLoaderRoute: typeof VenturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ventures/$slug': {
      id: '/ventures/$slug'
      path: '/ventures/$slug'
      fullPath: '/ventures/$slug'
      preLoaderRoute: typeof VenturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/standards': {
      id: '/about/standards'
      path: '/standards'
      fullPath: '/about/standards'
      preLoaderRoute: typeof AboutStandardsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/methodology': {
      id: '/about/methodology'
      path: '/methodology'
      fullPath: '/about/methodology'
      preLoaderRoute: typeof AboutMethodologyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/awards': {
      id: '/about/awards'
      path: '/awards'
      fullPath: '/about/awards'
      preLoaderRoute: typeof AboutAwardsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/$pillar': {
      id: '/about/$pillar'
      path: '/$pillar'
      fullPath: '/about/$pillar'
      preLoaderRoute: typeof AboutPillarRouteImport
      parentRoute: typeof AboutRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/pages/$page': {
      id: '/admin/pages/$page'
      path: '/$page'
      fullPath: '/admin/pages/$page'
      preLoaderRoute: typeof AdminPagesPageRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/cms/$type': {
      id: '/admin/cms/$type'
      path: '/$type'
      fullPath: '/admin/cms/$type'
      preLoaderRoute: typeof AdminCmsTypeRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/$type/': {
      id: '/admin/cms/$type/'
      path: '/'
      fullPath: '/admin/cms/$type/'
      preLoaderRoute: typeof AdminCmsTypeIndexRouteImport
      parentRoute: typeof AdminCmsTypeRoute
    }
    '/admin/cms/$type/$id': {
      id: '/admin/cms/$type/$id'
      path: '/$id'
      fullPath: '/admin/cms/$type/$id'
      preLoaderRoute: typeof AdminCmsTypeIdRouteImport
      parentRoute: typeof AdminCmsTypeRoute
    }
  }
}

interface AboutRouteChildren {
  AboutPillarRoute: typeof AboutPillarRoute
  AboutAwardsRoute: typeof AboutAwardsRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutMethodologyRoute: typeof AboutMethodologyRoute
  AboutStandardsRoute: typeof AboutStandardsRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutPillarRoute: AboutPillarRoute,
  AboutAwardsRoute: AboutAwardsRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutMethodologyRoute: AboutMethodologyRoute,
  AboutStandardsRoute: AboutStandardsRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AdminCmsTypeRouteChildren {
  AdminCmsTypeIdRoute: typeof AdminCmsTypeIdRoute
  AdminCmsTypeIndexRoute: typeof AdminCmsTypeIndexRoute
}

const AdminCmsTypeRouteChildren: AdminCmsTypeRouteChildren = {
  AdminCmsTypeIdRoute: AdminCmsTypeIdRoute,
  AdminCmsTypeIndexRoute: AdminCmsTypeIndexRoute,
}

const AdminCmsTypeRouteWithChildren = AdminCmsTypeRoute._addFileChildren(
  AdminCmsTypeRouteChildren,
)

interface AdminCmsRouteChildren {
  AdminCmsTypeRoute: typeof AdminCmsTypeRouteWithChildren
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsTypeRoute: AdminCmsTypeRouteWithChildren,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

interface AdminPagesRouteChildren {
  AdminPagesPageRoute: typeof AdminPagesPageRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageRoute: AdminPagesPageRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminDataRoute: typeof AdminDataRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminDataRoute: AdminDataRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApplicationStatusRoute: ApplicationStatusRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  PSlugRoute: PSlugRoute,
  VenturesSlugRoute: VenturesSlugRoute,
  VenturesIndexRoute: VenturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
